### ISSUE TITLE
Twich videos that are not Destiny 2 

### ISSUE THREAD

**Issue by Haplo88** [GuardianTheater/guardian-theater-indexeddb#21] opened 2020-10-11 23:38 UTC
Sometime videos are shown where the streamer is not playing destiny 2. My guess is they are having a recovery service carried out while they are streaming another game.
![GT](https://user-images.githubusercontent.com/72714267/95693250-1d785900-0c77-11eb-8ea9-433608c7a69b.jpg)

**Comment by Marthdovah** [comment] 2021-01-03 10:59
Sometimes the thumbnails show something else, but the timestamp would take you to when the match was played.

Other times?  Yeah, there's not one instance of them playing Destiny 2.

**Comment by Haplo88** [comment] 2021-01-09 21:15
No, I watched the videos, not destiny content - these videos are all diffrent gasmes, its not just the thumbnail

**Comment by garrettmorse** [comment] 2021-02-23 06:41
Also seeing the same issue. Some clips are perfect - recent comp match against a streamer, iron banner, etc. Most other clips are of random people playing Rocket League, Guitar Hero, etc.
 
![image](https://user-images.githubusercontent.com/47065587/108810075-49d2a900-7578-11eb-96a7-3ae6e5b92806.png)

**Comment by presstun** [comment] 2021-03-25 12:44
Same nothing but someone playing valorant

**Comment by chrisfried** [comment] 2021-04-05 14:03
They're false-positive matches. In the interest of finding as many Destiny clips as possible, the app attempts to match all the names linked to a Destiny account against Twitch names. The site finds more clips than it would if it just checked for explicitly linked Twitch accounts, but it also finds a lot of clips from accounts that don't actually match. There are a few paths forward, high on my list are:
- allow user to flag false-positives so they go away and don't come back
- allow user to opt to use the narrower search of only Twitch accounts that players have explicitly linked

**Comment by nazimamin** [comment] 2021-05-22 08:00
> They're false-positive matches. In the interest of finding as many Destiny clips as possible, the app attempts to match all the names linked to a Destiny account against Twitch names. The site finds more clips than it would if it just checked for explicitly linked Twitch accounts, but it also finds a lot of clips from accounts that don't actually match. There are a few paths forward, high on my list are:
> 
> * allow user to flag false-positives so they go away and don't come back
> * allow user to opt to use the narrower search of only Twitch accounts that players have explicitly linked

Is this caused by user/{id}/partnership API that provided linked Twitch account is no longer available on bungie's end?

**Comment by chrisfried** [comment] 2021-05-22 13:29
@nazimamin Yes, that was the reason for switching to a broader search which is prone to false-positives. However, Bungie has since re-implemented Twitch account linking to support Prime Gaming rewards.

I recently, silently switched the site over to only looking for those explicitly linked accounts. Which I suppose means I can close this ticket…

**Closed by chrisfried** 2021-05-22 13:29 UTC
