### ISSUE TITLE
Wrong videos

### ISSUE THREAD

**Issue by xPureOblivion** [GuardianTheater/guardian-theater-indexeddb#30] opened 2021-04-01 14:56 UTC
As someone else says, it seems that the twitch account is based off the steam account. Because they might have changed their name or something, this results in the wrong twitch account being shown. These streamers don't even play destiny. Hopefully this can be fixed soon

**Comment by chrisfried** [comment] 2021-04-05 14:14
Closing as duplicate of #21

**Closed by chrisfried** 2021-04-05 14:14 UTC
